#first plugin by XenialEmperus 
#don't change 
#only for internal use 
config-version: 2

#change values here 

profile: " "
fasttravel: " "
bank:  " "
job: " "
shop: " "
island: " 

# you ll get Copyright strike in posting or selling this plugin \DMCA
